image: Ubuntu

version: "7.0.1.{build}"

dotnet_csproj:
  version_prefix: "7.0.1"
  patch: true
  file: 'src\**\*.csproj'

configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: false

build_script:
  - pwsh: .\build.ps1

artifacts:
  - path: artifacts\packages\**\*.*nupkg
    name: MyGet
    type: NuGetPackage

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/autofac/api/v2/package
    symbol_server: https://www.myget.org/F/autofac/api/v2/package
    api_key:
      secure: xUXExgVAagrdEicCjSxsQVrwiLo2TtnfqMbYB9Cauq2cpbm/EVz957PBK0v/GEYq
    artifact: MyGet
